openapi: 3.0.3
info:
  title: sistemaPOS API
  version: 0.1.0
paths:
  /api/v1/payments/process:
    post:
      summary: Process a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                amount:
                  type: number
                currency:
                  type: string
                method:
                  type: string
      responses:
        '200':
          description: Payment processing started
  /api/v1/webhooks/stripe:
    post:
      summary: Stripe webhook endpoint
      responses:
        '200':
          description: OK
